### ISSUE TITLE
Not able to access services on Shadowsocks server when using Outline CLI

### ISSUE THREAD

**Issue by phpony** [Jigsaw-Code/outline-sdk#138]
I've just installed [Outline Cli](https://github.com/Jigsaw-Code/outline-sdk/tree/main/x/examples/outline-cli) and it does work on Debian 10. But there's a problem. After I run:

```
outline-cli -transport "ss://....?outline=1"
```

The server becomes inaccessible over the network.

I have Debian 10 with Ethernet interface called ens192 with public IP x.x.x.x. My gateway is x.x.x.1. Whenever i start outline new interface appears: outline233 with IP 10.233.233.1. Nothing changes is routes, them are same before and after connection:

```
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         x.x.x.1     0.0.0.0         UG    0      0        0 ens192
x.x.x.0     0.0.0.0         255.255.255.0   U     0      0        0 ens192
```

Nothing changes is iptables - no new rules or smth. But after connecting with outline I can have outgoing traffic from server but can't connect or even ping the server itself via x.x.x.x. 

How can I avoid this?

**Comment by phpony** [comment]
Well, seems like we intentionally blocking everything here https://github.com/Jigsaw-Code/outline-sdk/blob/6f0c166a4c9ac9b79224d85e01b6f4abbc53e458/x/examples/outline-cli/routing_linux.go#L106

Adding `return nil` as first line of `setupIpRule` fixes the problem. But is it safe? Why we block everything in the first place?

**Comment by jyyi1** [comment]
Hi @phpony , we are not blocking everything in the first place. You should still be able to access the internet. Here is how Outline CLI works:

1. We added a new routing table `233` (we won't touch the default routing table, because there might be a chance that we won't be able to recover it). You can list **all** routing rule for **all** routing tables in the system by `ip route show table all` (look for `table 233` in the response).
2. Then we routed all traffic to `table 233` to our tun device (i.e. `outline233`), Outline CLI will listen on this tun device and forward traffic to the target shadowsocks server. You can list the routing rule by `ip route show table 233`.
3. Finally, we must use the default routing table/network interface to forward the traffic to the target shadowsocks server  (otherwise there will be a dead loop). `ip rule list` will show `23333:	not from all to <ss-server-ip> lookup 233`, meaning all traffic to the `<ss-server-ip>` won't go through the routing table `233`.

I hope this could help you understand our routing strategy better, and give you more details to troubleshoot. Adding `return nil` to the code above basically means skipping step 3; and depending on the network interface and routing table configuration on the system, it might or might not work.

As the comment mentions, using `fwmark` would be better, but it requires a lot more effort. Therefore as a tradeoff, we used this simpler but still effective implementation.
